Исправление ошибки в проекте
HitmasterGames/area_test pull request #2
Opened 2024-06-12 21:00 UTC by HitmasterGames

Исправлены синтаксические ошибки

2024-06-12 21:05 UTC, f1erro0 commented
Что за извращение!!!!!!!

2024-06-12 21:05 UTC, f1erro0 commented
Что за извращение!!!!!!!

2024-06-12 21:11 UTC, f1erro0 requested changes
Что это за извращение

2024-06-12 21:14 UTC, shirowise approved these changes
Все хорошо, можно мержить

2024-06-13 21:38 UTC, f1erro0 requested changes
Почему не добавлен треугольник? Я займусь этим

2024-06-13 21:42 UTC, f1erro0 approved these changes
Zdorovo

2024-06-13 21:43 UTC, merged